name: Build and Release Debian Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/arm64

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Create Dockerfile
      run: |
        cat <<EOF > Dockerfile
        # syntax=docker/dockerfile:1
        FROM --platform=linux/arm64 ubuntu:20.04 as base

        ENV DEBIAN_FRONTEND=noninteractive
        RUN apt-get update && \
            apt-get install -y \
              build-essential \
              cmake \
              devscripts \
              debhelper \
              dh-exec \
              libdrm-dev \
              libtool \
              meson \
              pkg-config

        COPY . /src

        FROM base as deb_builder
        WORKDIR /src
        RUN debuild -us -uc -aarm64 -b
        EOF

    - name: Build Debian Package
      run: |
        docker buildx build --platform linux/arm64 -o type=local,dest=output --target deb_builder -f Dockerfile .

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release v2.2.0-${{ github.sha }}
        tag_name: v2.2.0-${{ github.sha }}
        generate_release_notes: true
        files: |
          ./output/librga-dev_2.2.0-1_arm64.deb
          ./output/librga2_2.2.0-1_arm64.deb
